### ISSUE TITLE
NameError: name '_C' is not defined`

### ISSUE THREAD

**Issue by sun123-cmd** [ok-robot/ok-robot#4]
I' m using cuda 11.8+torch2.1.0, same as our repo.
While running `python demo.py --debug`, I can choose pick/place and object. Then error occurs as `NameError: name '_C' is not defined`.
I try to run AnyGrasp and LangSam independently in the same environment. AnyGrasp can run successfully, but LangSam will have the following error:
`Traceback (most recent call last):
  File "/home/hs/sunwenhao/lang-segment-anything/running_test.py", line 12, in <module>
    masks, boxes, phrases, logits = model.predict(image_pil, text_prompt)
  File "/home/hs/sunwenhao/lang-segment-anything/lang_sam/lang_sam.py", line 118, in predict
    boxes, logits, phrases = self.predict_dino(image_pil, text_prompt, box_threshold, text_threshold)
  File "/home/hs/sunwenhao/lang-segment-anything/lang_sam/lang_sam.py", line 94, in predict_dino
    boxes, logits, phrases = predict(model=self.groundingdino,
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/groundingdino/util/inference.py", line 68, in predict
    outputs = model(image[None], captions=[caption])
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/groundingdino/models/GroundingDINO/groundingdino.py", line 327, in forward
    hs, reference, hs_enc, ref_enc, init_box_proposal = self.transformer(
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/groundingdino/models/GroundingDINO/transformer.py", line 258, in forward
    memory, memory_text = self.encoder(
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/groundingdino/models/GroundingDINO/transformer.py", line 576, in forward
    output = checkpoint.checkpoint(
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 451, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 230, in forward
    outputs = run_function(*args)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/groundingdino/models/GroundingDINO/transformer.py", line 785, in forward
    src2 = self.self_attn(
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 338, in forward
    output = MultiScaleDeformableAttnFunction.apply(
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/hs/miniconda3/envs/grasp-env/lib/python3.9/site-packages/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 53, in forward
    output = _C.ms_deform_attn_forward(
NameError: name '_C' is not defined`

**Comment by notmahi** [comment]
Looking at this thread from GroundingDINO, it seems like your torch may have been installed without GPU enabled? https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/15

In this case, you should ensure your torch/GroundingDINO is installed with GPU enabled by following the aforementioned issue.

**Comment by sun123-cmd** [comment]
> Looking at this thread from GroundingDINO, it seems like your torch may have been installed without GPU enabled? [IDEA-Research/Grounded-Segment-Anything#15](https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/15)
> 
> In this case, you should ensure your torch/GroundingDINO is installed with GPU enabled by following the aforementioned issue.

Thanks! I solved this problem by installing GroundingDINO, with 
```
python setup.py build
python setup.py install
```

**Comment by notmahi** [comment]
Glad to hear! Closing the issue since it’s solved.
